library(dygraphs)
library(ggplot2)
library(htmltools)
library(leaflet)
library(rmarkdown)
library(plyr)
library(readxl)
library(shiny)
library(shinydashboard)
library(zoo)
library(tidyr)
library(tidyverse)
library(uuid)
library(xts)
library(dplyr)
library(DT)
library(lubridate)

options(warn=-1)
options(digits=8)
borja_id_2019<-read.csv("https://www.dropbox.com/s/r0py2cyhchbnx3u/Noue_Dumont_Amont_Debit_2019.csv?dl=1", header=TRUE, sep=",",stringsAsFactors=FALSE)
borja_id_2018<-read.csv("https://www.dropbox.com/s/t50cvtiv7w51mfy/Noue_Dumont_Amont_Debit_2018.csv?dl=1", header=TRUE, sep=",",stringsAsFactors=FALSE)
borja_id_2017<-read.csv("https://www.dropbox.com/s/50b9d88odk585s7/Noue_Dumont_Amont_Debit_2017.csv?dl=1", header=TRUE, sep=",",stringsAsFactors=FALSE)

borja_dd_2019<-read.csv("https://www.dropbox.com/s/9kpbbkkdek3fwpx/Noue_Dumont_Aval_Debit_2019.csv?dl=1", header=TRUE, sep=",",stringsAsFactors=FALSE)
borja_dd_2018<-read.csv("https://www.dropbox.com/s/n8y6dwvq0psdov6/Noue_Dumont_Aval_Debit_2018.csv?dl=1", header=TRUE, sep=",",stringsAsFactors=FALSE)
borja_dd_2017<-read.csv("https://www.dropbox.com/s/czm5xoieumxko35/Noue_Dumont_Aval_Debit_2017.csv?dl=1", header=TRUE, sep=",",stringsAsFactors=FALSE)
borja_dd_2016<-read.csv("https://www.dropbox.com/s/e0q9nrjuyrccygi/Noue_Dumont_Aval_Debit_2016.csv?dl=1", header=TRUE, sep=",",stringsAsFactors=FALSE)
borja_dd_2015<-read.csv("https://www.dropbox.com/s/fsxkevpjmz3k5ht/Noue_Dumont_Aval_Debit_2015.csv?dl=1", header=TRUE, sep=",",stringsAsFactors=FALSE)
borja_dd_2014<-read.csv("https://www.dropbox.com/s/awbnq1ak21m8sai/Noue_Dumont_Aval_Debit_2014.csv?dl=1", header=TRUE, sep=",",stringsAsFactors=FALSE)
borja_dd_2013<-read.csv("https://www.dropbox.com/s/8jo42oo91f0upon/Noue_Dumont_Aval_Debit_2013.csv?dl=1", header=TRUE, sep=",",stringsAsFactors=FALSE)

borja_id_temp_2019 <-readRDS(gzcon(url("https://www.dropbox.com/s/e05kcsxcrlejmas/Noue_Dumont_Amont_Debit_2019_ord.rds?dl=1")))
borja_id_temp_2018 <-readRDS(gzcon(url("https://www.dropbox.com/s/sblx3umvlalnxel/Noue_Dumont_Amont_Debit_2018_ord.rds?dl=1")))
borja_id_temp_2017 <-readRDS(gzcon(url("https://www.dropbox.com/s/3q4zrlvamrqe7pc/Noue_Dumont_Amont_Debit_2017_ord.rds?dl=1")))
# 
# 
# 
borja_dd_temp_2019<-readRDS(gzcon(url("https://www.dropbox.com/s/7la68ktmi1a3bgs/Noue_Dumont_Aval_Debit_2019_ord.rds?dl=1")))
borja_dd_temp_2018<-readRDS(gzcon(url("https://www.dropbox.com/s/hsjfsy65lwj47h7/Noue_Dumont_Aval_Debit_2018_ord.rds?dl=1")))
borja_dd_temp_2017<-readRDS(gzcon(url("https://www.dropbox.com/s/umo18z6z5vp8qll/Noue_Dumont_Aval_Debit_2017_ord.rds?dl=1")))
borja_dd_temp_2016<-readRDS(gzcon(url("https://www.dropbox.com/s/hgs488o5j27zryn/Noue_Dumont_Aval_Debit_2016_ord.rds?dl=1")))
borja_dd_temp_2015<-readRDS(gzcon(url("https://www.dropbox.com/s/msm4shhq5xud2vl/Noue_Dumont_Aval_Debit_2015_ord.rds?dl=1")))
borja_dd_temp_2014<-readRDS(gzcon(url("https://www.dropbox.com/s/fs7h3nuo4xp9lt1/Noue_Dumont_Aval_Debit_2014_ord.rds?dl=1")))
borja_dd_temp_2013<-readRDS(gzcon(url("https://www.dropbox.com/s/1kh4wmbx299zatq/Noue_Dumont_Aval_Debit_2013_ord.rds?dl=1")))